#%RAML 1.0 DataType

description: Character data model.
type: object
additionalProperties: false
properties:
  name:
    displayName: Name
    description: Character name.
    type: string
  height:
    displayName: Height
    description: Character height.
    type: integer
  mass:
    displayName: Mass
    description: Character mass.
    type: integer
  hairColor:
    displayName: Hair color
    description: Character hair color.
    type: string
  skinColor:
    displayName: Skin color
    description: Character skin color.
    type: string
  eyeColor:
    displayName: Eye color
    description: Character eye color.
    type: string
  birthYear:
    displayName: Birth year
    description: Character birth year.
    type: string
  gender:
    displayName: Gender
    description: Character gender.
    type: string
  